# .golangci.yml
linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - errcheck
    - unused
    - typecheck

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
