# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# .goreleaser.yaml
version: 2

project_name: podpedia

builds:
  - env:
      - CGO_ENABLED=0
    hooks:
      pre: make plugins
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: podpedia
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - docs/**/*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^conductor:'

release:
  github:
    owner: gavmor
    name: podpedia
  draft: true
  prerelease: auto
  mode: replace
